// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using WeatherApp.Models;

namespace WeatherApp.Migrations
{
    [DbContext(typeof(WeatherContext))]
    partial class WeatherContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WeatherApp.Models.Weather", b =>
                {
                    b.Property<int>("ZIP");

                    b.Property<string>("City");

                    b.Property<string>("State");

                    b.Property<DateTime>("Day");

                    b.Property<decimal>("AirPressure");

                    b.Property<decimal>("FeelsLike");

                    b.Property<decimal>("Humidity");

                    b.Property<decimal>("Temperature");

                    b.Property<decimal>("UVIndex");

                    b.Property<decimal>("Visibility");

                    b.Property<decimal>("WindDirection");

                    b.Property<decimal>("WindSpeed");

                    b.HasKey("ZIP", "City", "State", "Day");

                    b.HasAlternateKey("City", "Day", "State", "ZIP");

                    b.ToTable("Weather");
                });
#pragma warning restore 612, 618
        }
    }
}
